"use client";

import { useMemo, useState } from "react";
import { Target } from "lucide-react";

import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { OpportunityFilters } from "@/components/opportunities/OpportunityFilters";
import { OpportunityTable } from "@/components/opportunities/OpportunityTable";
import { OpportunityCard } from "@/components/opportunities/OpportunityCard";
import { OpportunityDetails } from "@/components/opportunities/OpportunityDetails";
import { Modal } from "@/components/ui/Modal";
import { useDataset } from "@/hooks/useDataset";
import { useOpportunities } from "@/hooks/useOpportunities";
import { Opportunity } from "@/types/opportunity";

export default function OpportunitiesPage() {
  const { dataset } = useDataset();

  const {
    opportunities: apiOpportunities,
    loading,
    error,
  } = useOpportunities(
    dataset?.datasetId
  );

  const demoOpportunities: Opportunity[] = [
    {
      opportunity_id: "CHK-DROP-104",
      category: "RECOVER",
      opportunity_type: "Checkout Drop-off",
      customer_id: "CUST-104",
      amount_at_risk: 420000,
      probability: 0.82,
      expected_value: 344400,
      reason:
        "Checkout abandonment detected after payment initiation.",
      recommended_action:
        "Trigger a targeted payment recovery flow.",
      priority: "HIGH",
    },
    {
      opportunity_id: "PREVENT-CHURN-221",
      category: "PREVENT",
      opportunity_type: "Churn Risk",
      customer_id: "CUST-221",
      amount_at_risk: 210000,
      probability: 0.64,
      expected_value: 134400,
      reason:
        "Customer payment activity has materially declined.",
      recommended_action:
        "Engage the customer before the next renewal.",
      priority: "MEDIUM",
    },
    {
      opportunity_id: "SUB-FAIL-309",
      category: "RECOVER",
      opportunity_type: "Failed Subscription",
      customer_id: "CUST-309",
      amount_at_risk: 175000,
      probability: 0.76,
      expected_value: 133000,
      reason:
        "Subscription payment failed and remains recoverable.",
      recommended_action:
        "Retry the payment using the recommended recovery strategy.",
      priority: "HIGH",
    },
  ];

  const opportunities =
    apiOpportunities.length > 0
      ? apiOpportunities
      : demoOpportunities;

  const [category, setCategory] =
    useState("ALL");

  const [priority, setPriority] =
    useState("ALL");

  const [search, setSearch] =
    useState("");

  const [selected, setSelected] =
    useState<Opportunity | null>(null);

  const filtered = useMemo(() => {
    return opportunities.filter((item) => {
      const categoryMatch =
        category === "ALL" ||
        item.category === category;

      const priorityMatch =
        priority === "ALL" ||
        item.priority === priority;

      const query =
        search.toLowerCase().trim();

      const searchMatch =
        !query ||
        item.opportunity_type
          .toLowerCase()
          .includes(query) ||
        item.customer_id
          ?.toLowerCase()
          .includes(query);

      return (
        categoryMatch &&
        priorityMatch &&
        searchMatch
      );
    });
  }, [
    opportunities,
    category,
    priority,
    search,
  ]);

  return (
    <DashboardLayout>
      <div className="space-y-6">
        <section>
          <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-50 text-[#146ef5]">
            <Target size={23} />
          </div>

          <h1 className="mt-4 text-3xl font-bold tracking-tight text-slate-950">
            Revenue opportunities
          </h1>

          <p className="mt-2 text-sm text-slate-500">
            Prioritized actions generated by the intelligence engine.
          </p>
        </section>

        {!dataset && (
          <div className="rounded-2xl border border-amber-100 bg-amber-50 p-4 text-sm text-amber-700">
            No dataset uploaded yet. Showing demonstration
            opportunities.
          </div>
        )}

        {error && (
          <div className="rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm text-blue-700">
            Backend opportunity endpoint is not enabled yet.
            Showing the dashboard demo data.
          </div>
        )}

        {loading && (
          <div className="rounded-2xl border border-slate-200 bg-white p-5 text-sm text-slate-500">
            Loading opportunities...
          </div>
        )}

        <OpportunityFilters
          category={category}
          priority={priority}
          search={search}
          onCategoryChange={setCategory}
          onPriorityChange={setPriority}
          onSearchChange={setSearch}
        />

        <div className="hidden lg:block">
          <OpportunityTable
            opportunities={filtered}
            onSelect={setSelected}
          />
        </div>

        <div className="grid gap-4 lg:hidden">
          {filtered.map((item) => (
            <OpportunityCard
              key={item.opportunity_id}
              opportunity={item}
              onClick={() =>
                setSelected(item)
              }
            />
          ))}
        </div>

        <Modal
          open={Boolean(selected)}
          title="Opportunity details"
          onClose={() => setSelected(null)}
        >
          {selected && (
            <OpportunityDetails
              opportunity={selected}
            />
          )}
        </Modal>
      </div>
    </DashboardLayout>
  );
}